/**
 * statement status 
 */
const ACCOUNT_STATEMENT_STATUS_TYPES = {
	PROGRESS: 3,
	FINISH: 4,
	REFUSE: 5,
};

const ACCOUNT_STATEMENT_STATUS_TEXT = {
	[ACCOUNT_STATEMENT_STATUS_TYPES.PROGRESS]: 'statement.progress',
	[ACCOUNT_STATEMENT_STATUS_TYPES.FINISH]: 'statement.finish',
	[ACCOUNT_STATEMENT_STATUS_TYPES.REFUSE]: 'statement.refuse',
};

const ACCOUNT_STATEMENT_STATUS = {
	PROGRESS: {
		value: ACCOUNT_STATEMENT_STATUS_TYPES.PROGRESS,
		label: ACCOUNT_STATEMENT_STATUS_TEXT[ACCOUNT_STATEMENT_STATUS_TYPES.PROGRESS],
	},
	FINISH: {
		value: ACCOUNT_STATEMENT_STATUS_TYPES.FINISH,
		label: ACCOUNT_STATEMENT_STATUS_TEXT[ACCOUNT_STATEMENT_STATUS_TYPES.FINISH],
	},
	REFUSE: {
		value: ACCOUNT_STATEMENT_STATUS_TYPES.REFUSE,
		label: ACCOUNT_STATEMENT_STATUS_TEXT[ACCOUNT_STATEMENT_STATUS_TYPES.REFUSE],
	},
};

/**
 * STATMENT類型
 */
const ACCOUNT_STATEMENT_TYPES = {
	USDT_RECHARGE: 1,
	USDT_WITHDRAWAL: 2,
	USDT_TO_BAMBOO: 3,
	USDT_FROM_BAMBOO: 4,
	BAMBOO_TO_USDT: 5,
	BAMBOO_FROM_USDT: 6,
	BAMBOO_TO_LPG:7,
	BAMBOO_WINNING_INCOME: 8,
	BAMBOO_FEED: 9,
	BAMBOO_TRANS_INCOME: 10,
	BAMBOO_TRANS_EXPEND: 11,
	AIRDROP_TICKET_BAMBOO_FEED_REDEEM: 12,
	AIRDROP_TICKET_USE_FOR_LPG: 13,
	RAFFLE_TICKET_BAMBOO_FEED_REDEEM: 14,
	RAFFLE_TICKET_PARTICIPATE_RAFFLE: 15,
	LPG_RECHARGE: 16,
	LPG_WITHDRAWAL: 17,
	LPG_FROM_BAMBOO: 18,
	LPG_FROM_AIRDROP: 19,
	BAMBOO_COOPERATE_INCOME: 20,
	LPG_SHARE_REWARD: 21,
	USDT_FEE_FOR_LPG_WITHDRAW: 22,
	USDT_RETURN_FOR_USDT_WITHDRAW_FAIL: 23,
	USDT_RETURN_LPG_WITHDRAW_FAIL_FEE: 24,
	LPG_RETURN_LPG_WITHDRAW_FAIL: 25
};

const ACCOUNT_STATEMENT_TYPE_TEXT = {
	[ACCOUNT_STATEMENT_TYPES.USDT_RECHARGE]: 'statement.usdtRecharge',
	[ACCOUNT_STATEMENT_TYPES.USDT_WITHDRAWAL]: 'statement.usdtWithdrawal',
	[ACCOUNT_STATEMENT_TYPES.USDT_TO_BAMBOO]: 'statement.usdtToBamboo',
	[ACCOUNT_STATEMENT_TYPES.USDT_FROM_BAMBOO]: 'statement.usdtFromBamboo',
	[ACCOUNT_STATEMENT_TYPES.BAMBOO_TO_USDT]: 'statement.bambooToUsdt',
	[ACCOUNT_STATEMENT_TYPES.BAMBOO_FROM_USDT]: 'statement.bambooFromUsdt',
	[ACCOUNT_STATEMENT_TYPES.BAMBOO_TO_LPG]: 'statement.bambooToLpg',
	[ACCOUNT_STATEMENT_TYPES.BAMBOO_WINNING_INCOME]: 'statement.bambooWinningIncome',
	[ACCOUNT_STATEMENT_TYPES.BAMBOO_FEED]: 'statement.bambooFeed',
	[ACCOUNT_STATEMENT_TYPES.BAMBOO_TRANS_INCOME]: 'statement.bambooTransIncome',
	[ACCOUNT_STATEMENT_TYPES.BAMBOO_TRANS_EXPEND]: 'statement.bambooTransExpend',
	[ACCOUNT_STATEMENT_TYPES.AIRDROP_TICKET_BAMBOO_FEED_REDEEM]: 'statement.airdropTicketBambooFeedRedeem',
	[ACCOUNT_STATEMENT_TYPES.AIRDROP_TICKET_USE_FOR_LPG]: 'statement.airdropTicketUseForLpg',
	[ACCOUNT_STATEMENT_TYPES.RAFFLE_TICKET_BAMBOO_FEED_REDEEM]: 'statement.raffleTicketBambooFeedRedeem',
	[ACCOUNT_STATEMENT_TYPES.RAFFLE_TICKET_PARTICIPATE_RAFFLE]: 'statement.raffleTicketParticipateRaffle',
	[ACCOUNT_STATEMENT_TYPES.LPG_RECHARGE]: 'statement.lpgRecharge',
	[ACCOUNT_STATEMENT_TYPES.LPG_WITHDRAWAL]: 'statement.lpgWithdrawal',
	[ACCOUNT_STATEMENT_TYPES.LPG_FROM_BAMBOO]: 'statement.lpgFromBamboo',
	[ACCOUNT_STATEMENT_TYPES.LPG_FROM_AIRDROP]: 'statement.lpgFromAirdrop',
	[ACCOUNT_STATEMENT_TYPES.BAMBOO_COOPERATE_INCOME]: 'statement.bambooCooperateIncome',
	[ACCOUNT_STATEMENT_TYPES.LPG_SHARE_REWARD]: 'statement.lpgShareReward',
	[ACCOUNT_STATEMENT_TYPES.USDT_FEE_FOR_LPG_WITHDRAW]: 'statement.usdtFeeForLpgWithdrawal',
	[ACCOUNT_STATEMENT_TYPES.USDT_RETURN_FOR_USDT_WITHDRAW_FAIL]: 'statement.usdtReturnForUsdtWithdrawFail',
	[ACCOUNT_STATEMENT_TYPES.USDT_RETURN_LPG_WITHDRAW_FAIL_FEE]: 'statement.usdtReturnLpgWithdrawFailFee',
	[ACCOUNT_STATEMENT_TYPES.LPG_RETURN_LPG_WITHDRAW_FAIL]: 'statement.lpgReturnLpgWithdrawFail',
};

const ACCOUNT_STATEMENT_TYPE_ITEMS = {
	USDT_RECHARGE: {
		value: ACCOUNT_STATEMENT_TYPES.USDT_RECHARGE,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.USDT_RECHARGE],
	},
	USDT_WITHDRAWAL: {
		value: ACCOUNT_STATEMENT_TYPES.USDT_WITHDRAWAL,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.USDT_WITHDRAWAL],
	},
	USDT_TO_BAMBOO: {
		value: ACCOUNT_STATEMENT_TYPES.USDT_TO_BAMBOO,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.USDT_TO_BAMBOO],
	},
	USDT_FROM_BAMBOO: {
		value: ACCOUNT_STATEMENT_TYPES.USDT_FROM_BAMBOO,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.USDT_FROM_BAMBOO],
	},
	BAMBOO_TO_USDT: {
		value: ACCOUNT_STATEMENT_TYPES.BAMBOO_TO_USDT,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.BAMBOO_TO_USDT],
	},
	BAMBOO_FROM_USDT: {
		value: ACCOUNT_STATEMENT_TYPES.BAMBOO_FROM_USDT,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.BAMBOO_FROM_USDT],
	},
	BAMBOO_TO_LPG: {
		value: ACCOUNT_STATEMENT_TYPES.BAMBOO_TO_LPG,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.BAMBOO_TO_LPG],
	},
	BAMBOO_WINNING_INCOME: {
		value: ACCOUNT_STATEMENT_TYPES.BAMBOO_WINNING_INCOME,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.BAMBOO_WINNING_INCOME],
	},
	BAMBOO_FEED: {
		value: ACCOUNT_STATEMENT_TYPES.BAMBOO_FEED,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.BAMBOO_FEED],
	},
	BAMBOO_TRANS_INCOME: {
		value: ACCOUNT_STATEMENT_TYPES.BAMBOO_TRANS_INCOME,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.BAMBOO_TRANS_INCOME],
	},
	BAMBOO_TRANS_EXPEND: {
		value: ACCOUNT_STATEMENT_TYPES.BAMBOO_TRANS_EXPEND,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.BAMBOO_TRANS_EXPEND],
	},
	AIRDROP_TICKET_BAMBOO_FEED_REDEEM: {
		value: ACCOUNT_STATEMENT_TYPES.AIRDROP_TICKET_BAMBOO_FEED_REDEEM,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.AIRDROP_TICKET_BAMBOO_FEED_REDEEM],
	},
	AIRDROP_TICKET_USE_FOR_LPG: {
		value: ACCOUNT_STATEMENT_TYPES.AIRDROP_TICKET_USE_FOR_LPG,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.AIRDROP_TICKET_USE_FOR_LPG],
	},
	RAFFLE_TICKET_BAMBOO_FEED_REDEEM: {
		value: ACCOUNT_STATEMENT_TYPES.RAFFLE_TICKET_BAMBOO_FEED_REDEEM,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.RAFFLE_TICKET_BAMBOO_FEED_REDEEM],
	},
	RAFFLE_TICKET_PARTICIPATE_RAFFLE: {
		value: ACCOUNT_STATEMENT_TYPES.RAFFLE_TICKET_PARTICIPATE_RAFFLE,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.RAFFLE_TICKET_PARTICIPATE_RAFFLE],
	},
	LPG_RECHARGE: {
		value: ACCOUNT_STATEMENT_TYPES.LPG_RECHARGE,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.LPG_RECHARGE],
	},
	LPG_WITHDRAWAL: {
		value: ACCOUNT_STATEMENT_TYPES.LPG_WITHDRAWAL,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.LPG_WITHDRAWAL],
	},
	LPG_FROM_BAMBOO: {
		value: ACCOUNT_STATEMENT_TYPES.LPG_FROM_BAMBOO,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.LPG_FROM_BAMBOO],
	},
	LPG_FROM_AIRDROP: {
		value: ACCOUNT_STATEMENT_TYPES.LPG_FROM_AIRDROP,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.LPG_FROM_AIRDROP],
	},
	BAMBOO_COOPERATE_INCOME: {
		value: ACCOUNT_STATEMENT_TYPES.BAMBOO_COOPERATE_INCOME,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.BAMBOO_COOPERATE_INCOME],
	},
	LPG_SHARE_REWARD: {
		value: ACCOUNT_STATEMENT_TYPES.LPG_SHARE_REWARD,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.LPG_SHARE_REWARD],
	},
	USDT_FEE_FOR_LPG_WITHDRAW: {
		value: ACCOUNT_STATEMENT_TYPES.USDT_FEE_FOR_LPG_WITHDRAW,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.USDT_FEE_FOR_LPG_WITHDRAW],
	},
	USDT_RETURN_FOR_USDT_WITHDRAW_FAIL: {
		value: ACCOUNT_STATEMENT_TYPES.USDT_RETURN_FOR_USDT_WITHDRAW_FAIL,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.USDT_RETURN_FOR_USDT_WITHDRAW_FAIL],
	},
	USDT_RETURN_LPG_WITHDRAW_FAIL_FEE: {
		value: ACCOUNT_STATEMENT_TYPES.USDT_RETURN_LPG_WITHDRAW_FAIL_FEE,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.USDT_RETURN_LPG_WITHDRAW_FAIL_FEE],
	},
	LPG_RETURN_LPG_WITHDRAW_FAIL: {
		value: ACCOUNT_STATEMENT_TYPES.LPG_RETURN_LPG_WITHDRAW_FAIL,
		label: ACCOUNT_STATEMENT_TYPE_TEXT[ACCOUNT_STATEMENT_TYPES.LPG_RETURN_LPG_WITHDRAW_FAIL],
	},
};
export default {
	ACCOUNT_STATEMENT_STATUS_TYPES,
	ACCOUNT_STATEMENT_STATUS_TEXT,
	ACCOUNT_STATEMENT_STATUS,
	ACCOUNT_STATEMENT_TYPES,
	ACCOUNT_STATEMENT_TYPE_TEXT,
	ACCOUNT_STATEMENT_TYPE_ITEMS
}