const AMOUNT_TYPE_TYPES = {
	USDT: 1,
	BAMBOO: 2,
	RAFFLE_TICKET: 3,
	LPG: 4,
	AIRDROP_TICKET: 5,
};

const AMOUNT_TYPE_TEXT = {
	[AMOUNT_TYPE_TYPES.USDT]: 'amount.usdt',
	[AMOUNT_TYPE_TYPES.BAMBOO]: 'amount.bamboo',
	[AMOUNT_TYPE_TYPES.RAFFLE_TICKET]: 'amount.raffleTicket',
	[AMOUNT_TYPE_TYPES.LPG]: 'amount.lpg',
	[AMOUNT_TYPE_TYPES.AIRDROP_TICKET]: 'amount.airdropTicket',
};

const AMOUNT_TYPE_ITEMS = {
	USDT: {
		value: AMOUNT_TYPE_TYPES.USDT,
		label: AMOUNT_TYPE_TEXT[AMOUNT_TYPE_TYPES.USDT],
	},
	BAMBOO: {
		value: AMOUNT_TYPE_TYPES.BAMBOO,
		label: AMOUNT_TYPE_TEXT[AMOUNT_TYPE_TYPES.BAMBOO],
	},
	RAFFLE_TICKET: {
		value: AMOUNT_TYPE_TYPES.RAFFLE_TICKET,
		label: AMOUNT_TYPE_TEXT[AMOUNT_TYPE_TYPES.RAFFLE_TICKET],
	},
	LPG: {
		value: AMOUNT_TYPE_TYPES.LPG,
		label: AMOUNT_TYPE_TEXT[AMOUNT_TYPE_TYPES.LPG],
	},
	AIRDROP_TICKET: {
		value: AMOUNT_TYPE_TYPES.AIRDROP_TICKET,
		label: AMOUNT_TYPE_TEXT[AMOUNT_TYPE_TYPES.AIRDROP_TICKET],
	},
};

export default {
	AMOUNT_TYPE_TYPES,
	AMOUNT_TYPE_TEXT,
	AMOUNT_TYPE_ITEMS,
}
