const SHARE_REWARD_SOURCE_TYPES = {
	BAMBOO_TRANS_LPG: 1,
	AIRDROP: 2,
};

const SHARE_REWARD_SOURCE_TEXT = {
	[SHARE_REWARD_SOURCE_TYPES.BAMBOO_TRANS_LPG]: 'share.rewardSource.bambooTransLpg',
	[SHARE_REWARD_SOURCE_TYPES.AIRDROP]: 'share.rewardSource.airdrop',
};

const SHARE_REWARD_SOURCE_ITMES = {
	BAMBOO_TRANS_LPG: {
		value: SHARE_REWARD_SOURCE_TYPES.BAMBOO_TRANS_LPG,
		label: SHARE_REWARD_SOURCE_TEXT[SHARE_REWARD_SOURCE_TYPES.BAMBOO_TRANS_LPG],
	},
	AIRDROP: {
		value: SHARE_REWARD_SOURCE_TYPES.AIRDROP,
		label: SHARE_REWARD_SOURCE_TEXT[SHARE_REWARD_SOURCE_TYPES.AIRDROP],
	}
};

export default {
	SHARE_REWARD_SOURCE_TYPES,
	SHARE_REWARD_SOURCE_TEXT,
	SHARE_REWARD_SOURCE_ITMES
}